name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: ./deploy.sh
        env:
              ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
